---
id: notifyOnNewOrcaSlicerRelease
namespace: releases

triggers:
  - id: schedule_trigger
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "*/5 * * * *"

tasks:
  - id: get_last_release
    type: io.kestra.plugin.core.kv.Get
    key: orcaslicer_last_release
    errorOnMissing: false

  - id: fetch_latest_release
    type: io.kestra.plugin.core.flow.Subflow
    namespace: releases
    flowId: fetchLatestGitHubRelease
    inputs:
      repository_owner: SoftFever
      repository: OrcaSlicer
    wait: true
    transmitFailed: true

  - id: get_published_at_timestamp
    type: io.kestra.plugin.core.debug.Return
    format: "{{ outputs.fetch_latest_release.outputs.release[0].published_at | timestamp() }}"

  - id: decide_notify
    type: io.kestra.plugin.core.flow.Switch
    value: "{{ (outputs.get_published_at_timestamp.value | number('LONG')) > (outputs.get_last_release.value | default('0') | number('LONG')) }}"
    cases:
      true:
        - id: notify_bjws_discord
          type: io.kestra.plugin.notifications.discord.DiscordIncomingWebhook
          url: "{{ secret('DISCORD_WEBHOOK_BJWS_RELEASES') }}"
          payload: |
            {
              "content": "A new OrcaSlicer version has been released!",
              "username": "OrcaSlicer",
              "avatar_url": "https://wiki.bambulab.com/admin/home/logo-large.png",
              "embeds": [
                {
                  "title": "OrcaSlicer release {{ outputs.fetch_latest_release.outputs.release[0].tag_name }}",
                  "url": "{{ outputs.fetch_latest_release.outputs.release[0].html_url }}",
                  "thumbnail": {
                    "url": "https://wiki.bambulab.com/admin/home/logo-large.png"
                  },
                  "color": "2467139",
                  "fields": [
                    {
                      "name": "Published",
                      "value": "{{ outputs.fetch_latest_release.outputs.release[0].published_at }}"
                    },
                    {
                      "name": "Release link",
                      "value": "{{ outputs.fetch_latest_release.outputs.release[0].html_url }}"
                    }
                  ]
                }
              ]
            }

        - id: store_last_release
          type: io.kestra.plugin.core.kv.Set
          key: orcaslicer_last_release
          value: "{{ outputs.get_published_at_timestamp.value }}"

    defaults:
      - id: no-op
        type: io.kestra.plugin.core.log.Log
        message: "Nothing to do"
